version: "3.8"

services:
  kepstroy-site:
    build: .
    container_name: kepstroy-site
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kepstroy.rule=Host(`kepstroy.ru`) || Host(`www.kepstroy.ru`)"
      - "traefik.http.routers.kepstroy.entrypoints=websecure"
      - "traefik.http.routers.kepstroy.tls.certresolver=letsencrypt"
      - "traefik.http.services.kepstroy.loadbalancer.server.port=80"
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.http.middlewares.kepstroy-redirect-www.redirectregex.regex=^https://www\\.kepstroy\\.ru/(.*)"
      - "traefik.http.middlewares.kepstroy-redirect-www.redirectregex.replacement=https://kepstroy.ru/$${1}"
      - "traefik.http.middlewares.kepstroy-redirect-www.redirectregex.permanent=true"
      - "traefik.http.routers.kepstroy.middlewares=kepstroy-redirect-www"
    networks:
      - web
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  web:
    external: true
